const API="https://countries.dev/countries?fields=name,capital,flag,alpha2Code,independent",N=5,T=15,POINTS={easy:1,medium:2,hard:3},E=new Set(["Australia","Brazil","Canada","China","Egypt","France","Germany","India","Italy","Japan","Mexico","New Zealand","South Africa","Spain","United States of America"]),M=new Set(["Argentina","Austria","Bangladesh","Chile","Colombia","Greece","Indonesia","Kenya","Morocco","Nigeria","Norway","Pakistan","Peru","Portugal","South Korea","Thailand","Turkey"]),$=s=>document.querySelector(s);
const start=$("#start-screen"),quiz=$("#quiz-screen"),result=$("#result-screen"),form=$("#game-settings"),startBtn=$("#start-btn"),restart=$("#restart-btn"),next=$("#next-btn"),quit=$("#quit-btn"),home=$("#home-btn"),brandHome=$("#brand-home"),reviewBtn=$("#review-btn"),share=$("#share-btn"),themeBtn=$("#theme-toggle"),themeIcon=$("#theme-icon"),themeLabel=$("#theme-label"),difficulty=$("#difficulty"),mode=$("#quiz-mode"),loading=$("#loading-state"),error=$("#start-error"),questionText=$("#question-text"),flagCard=$("#flag-display"),flagImage=$("#flag-image"),flagFallback=$("#flag-fallback"),answers=$("#answer-containers"),feedback=$("#answer-feedback"),feedbackTitle=$("#feedback-heading"),feedbackText=$("#feedback-text"),feedbackFlag=$("#feedback-flag"),current=$("#current-question"),total=$("#total-questions"),category=$("#category"),scoreEl=$("#score"),streakEl=$("#streak"),progress=$("#progress"),timerCard=$("#timer-card"),timerText=$("#timer-text"),timerFill=$("#timer-fill"),final=$("#final-score"),max=$("#max-score"),correct=$("#correct-count"),count=$("#question-count"),meter=$("#score-meter"),resultDifficulty=$("#result-difficulty"),resultMode=$("#result-mode"),bestStreak=$("#best-streak"),newBest=$("#new-best"),reviewPanel=$("#review-panel"),reviewList=$("#review-list"),shareStatus=$("#share-status"),message=$("#result-message"),best=$("#best-score"),themeMeta=$("meta[name='theme-color']");
let countries=[],questions=[],index=0,score=0,streak=0,corrects=0,topStreak=0,misses=[],chosen=false,time=T,interval,audio;
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const cap=s=>s[0].toUpperCase()+s.slice(1);
const screen=x=>[start,quiz,result].forEach(s=>s.classList.toggle("active",s===x));
function theme(dark){document.body.classList.toggle("dark",dark);themeIcon.textContent=dark?"☀":"☾";themeLabel.textContent=dark?"Light":"Dark";themeMeta.content=dark?"#08101e":"#edf3ff"}function initTheme(){const x=localStorage.getItem("geoQuestTheme");theme(x?x==="dark":matchMedia("(prefers-color-scheme: dark)").matches)}function toggleTheme(){const x=!document.body.classList.contains("dark");localStorage.setItem("geoQuestTheme",x?"dark":"light");theme(x)}
function sound(ok){try{audio??=new AudioContext;const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime;o.frequency.setValueAtTime(ok?560:180,n);o.frequency.exponentialRampToValueAtTime(ok?760:110,n+.16);g.gain.setValueAtTime(.08,n);g.gain.exponentialRampToValueAtTime(.001,n+.18);o.connect(g).connect(audio.destination);o.start(n);o.stop(n+.18)}catch{}}
async function loadCountries(){if(countries.length)return;const r=await fetch(API);if(!r.ok)throw Error();countries=(await r.json()).filter(c=>c.independent&&c.name&&c.capital&&c.flag);if(countries.length<N)throw Error()}
const pool=()=>difficulty.value==="easy"?countries.filter(c=>E.has(c.name)):difficulty.value==="medium"?countries.filter(c=>M.has(c.name)):countries.filter(c=>!E.has(c.name)&&!M.has(c.name));
const options=(c,get,p)=>shuffle([get(c),...[...new Set(shuffle(p.map(get).filter(x=>x!==get(c))))].slice(0,3)]);
function makeQuestions(p){return shuffle(p).slice(0,N).map((c,i)=>{const flag=mode.value==="flags"||(mode.value==="mixed"&&i%2);return{question:flag?"Which country does this flag belong to?":`What is the capital of ${c.name}?`,category:flag?"Flags":"Capital cities",flag:c.flag,url:c.alpha2Code?`https://flagcdn.com/w320/${c.alpha2Code.toLowerCase()}.png`:"",country:c.name,capital:c.capital,answers:flag?options(c,x=>x.name,p):options(c,x=>x.capital,p),correct:flag?c.name:c.capital}})}
function busy(x){startBtn.disabled=x;difficulty.disabled=x;mode.disabled=x;startBtn.querySelector("span").textContent=x?"Preparing your quiz":"Start expedition";loading.hidden=!x}
function stopTimer(){clearInterval(interval)}function timer(){timerText.textContent=`00:${String(time).padStart(2,"0")}`;timerFill.style.width=`${time/T*100}%`;timerCard.classList.toggle("warning",time<=5)}function startTimer(){stopTimer();time=T;timer();interval=setInterval(()=>{time--;timer();if(time<=0){stopTimer();answer(null,"",true)}},1000)}
async function startGame(e){e?.preventDefault();busy(true);error.hidden=true;try{await loadCountries();const p=pool();if(p.length<N)throw Error();questions=makeQuestions(p);index=score=streak=corrects=topStreak=0;misses=[];scoreEl.textContent=0;streakEl.textContent=0;total.textContent=N;screen(quiz);showQuestion()}catch{error.textContent="We couldn't load country data. Check your connection and try again.";error.hidden=false}finally{busy(false)}}
function showQuestion(){chosen=false;const q=questions[index];questionText.textContent=q.question;category.textContent=q.category;current.textContent=index+1;progress.style.width=`${index/N*100}%`;feedback.hidden=next.hidden=true;flagCard.hidden=q.category!=="Flags";flagImage.hidden=!q.url;flagFallback.hidden=!!q.url;flagFallback.textContent=q.flag;if(q.url)flagImage.src=q.url;answers.replaceChildren();q.answers.forEach((a,i)=>{const b=document.createElement("button"),k=document.createElement("span"),t=document.createElement("span");b.className="answer-btn";b.type="button";b.dataset.answer=a;k.className="answer-key";k.textContent=String.fromCharCode(65+i);t.textContent=a;b.append(k,t);b.onclick=()=>answer(b,a);answers.append(b)});startTimer()}
function showFeedback(q,ok,points,timeout){feedback.className=`feedback ${ok?"success":"error"}`;feedbackTitle.textContent=ok?`Correct · +${points} points${streak>1?` · ${streak} streak`:""}`:timeout?"Time's up · streak reset":"Not quite · streak reset";feedbackText.textContent=`${q.country} — capital: ${q.capital}`;feedbackFlag.textContent=q.flag;feedback.hidden=false}
function answer(button,value,timeout=false){if(chosen)return;chosen=true;stopTimer();const q=questions[index],ok=!timeout&&value===q.correct;answers.querySelectorAll("button").forEach(b=>{b.disabled=true;if(b.dataset.answer===q.correct)b.classList.add("correct")});let points=0;if(ok){streak++;topStreak=Math.max(topStreak,streak);corrects++;points=POINTS[difficulty.value]+streak-1;score+=points;scoreEl.textContent=score}else{streak=0;misses.push({...q,selected:timeout?"Time ran out":value});button?.classList.add("incorrect")}streakEl.textContent=streak;sound(ok);showFeedback(q,ok,points,timeout);next.querySelector("span").textContent=index===N-1?"See results":"Next question";next.hidden=false}
function nextQuestion(){index++;index<N?showQuestion():showResults()}
function showResults(){const p=corrects/N*100,b=POINTS[difficulty.value]*N,m=b+N*(N-1)/2,old=+localStorage.getItem("geoQuestBestScore")||0;final.textContent=score;max.textContent=m;correct.textContent=corrects;count.textContent=N;bestStreak.textContent=topStreak;resultDifficulty.textContent=`${cap(difficulty.value)} level`;resultMode.textContent=mode.options[mode.selectedIndex].text.split(" · ")[0];meter.replaceChildren(...Array.from({length:N},(_,i)=>{const x=document.createElement("span");x.className=i<corrects?"filled":"";return x}));reviewBtn.hidden=!misses.length;reviewBtn.textContent="Review missed questions";reviewPanel.hidden=true;shareStatus.textContent="";progress.style.width="100%";newBest.hidden=score<=old;if(score>old){localStorage.setItem("geoQuestBestScore",score);best.textContent=score}message.textContent=p===100?"Perfect route. You know this world.":p>=70?"Excellent work. Your map knowledge is growing.":p>=40?"Solid exploration. Keep charting new territory.":"Every great explorer starts with one route.";screen(result)}
function goHome(){stopTimer();screen(start)}
function review(){reviewList.replaceChildren(...misses.map(q=>{const a=document.createElement("article"),f=document.createElement("span"),d=document.createElement("div");a.className="review-item";f.className="review-flag";f.textContent=q.flag;d.innerHTML=`<h3>${q.country}</h3><p>Capital: ${q.capital}</p><p>Your answer: ${q.selected}</p>`;a.append(f,d);return a}));reviewPanel.hidden=!reviewPanel.hidden;reviewBtn.textContent=reviewPanel.hidden?"Review missed questions":"Hide review"}
async function copy(){const x=`I scored ${score} points with ${corrects}/${N} correct answers on GeoQuest (${difficulty.value} · ${mode.value}).`;try{await navigator.clipboard.writeText(x);shareStatus.textContent="Round result copied to your clipboard."}catch{shareStatus.textContent=x}}
flagImage.onerror=()=>{flagImage.hidden=true;flagFallback.hidden=false};form.onsubmit=startGame;restart.onclick=startGame;next.onclick=nextQuestion;quit.onclick=home.onclick=brandHome.onclick=goHome;reviewBtn.onclick=review;share.onclick=copy;themeBtn.onclick=toggleTheme;initTheme();best.textContent=localStorage.getItem("geoQuestBestScore")||"0";